version: "3.9"
services:
  site1:
    build: .
    container_name: site1
    expose:
      - "80"
    restart: unless-stopped

  site2:
    build: .
    container_name: site2
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/2_4.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - site1
      - site2
    restart: unless-stopped 