version: "3.9"
services:
  site1:
    build: .
    container_name: site1
    ports:
      - "8001:80"
    restart: unless-stopped

  site2:
    build: .
    container_name: site2
    ports:
      - "8002:80"
    restart: unless-stopped 