version: "3.9"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: app1
    expose:
      - "80"

  app2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: app2
    expose:
      - "80"
      
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/2_4.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
    restart: unless-stopped 