version: "3.9"
services:
  web:
    build: .
    container_name: web_multi_port
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_multi_port
    ports:
      - "80:80"
      - "1337:1337"
      - "1338:1338"
    volumes:
      - ./nginx/conf.d/2_2.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped 