version: "3.9"
services:
  site1:
    build:
      context: .
      dockerfile: Dockerfile1
      args:
        APP_DIR: src1
    container_name: site1
    expose:
      - "80"

  site2:
    build:
      context: .
      dockerfile: Dockerfile2
      args:
        APP_DIR: src2
    container_name: site2
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx_multi_site
    ports:
      - "1337:1337"
      - "1338:1338"
    volumes:
      - ./nginx/conf.d/2_3.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - site1
      - site2
    restart: unless-stopped 